### ISSUE TITLE
websocket 经常会断开连接

### ISSUE THREAD

**Issue by wisdomboy** [jwdeveloper/TikTokLiveJava#100]
websocket连接上TK后，隔一段时间会断开连接，出现这种情况的频率也是挺高的，为什么？api 版本1.8.5

English: After websocket is connected to TT, the connection will be disconnected after a period of time. The frequency of this situation is also quite high. Why? api version 1.8.5

**Comment by kohlerpop1** [comment]
This is a TikTok thing that we cannot control. Best you can do is reconnect after 5-10 seconds of disconnection.
