### ISSUE TITLE
 Checked that the anchor is not online?

### ISSUE THREAD

**Issue by wisdomboy** [jwdeveloper/TikTokLiveJava#103]
The live broadcast room is in the broadcast state, but when the service is turned on, it prompts that the anchor is not online. The method called TikTokLive.isLiveOnline(liveUsername)。Through the browser, analyze the webpage code of the live broadcast room and cannot find the roomId parameter.

**Comment by kohlerpop1** [comment]
Our code does not scrape the webpage for the roomId.

**Comment by wisdomboy** [comment]
> Our code does not scrape the webpage for the roomId.

yes ,it does not scrape the webpage for the roomId。Why does calling the TikTokLive. isLiveOnline (liveUsername) method when the anchor is in the broadcasting state prompt that the user does not exist or is not online? thanks for answer me

**Comment by kohlerpop1** [comment]
This usually only occurs when the account is set to private or the name is misspelled. Other than that, this should not occur. Share me the name and I will look into it.

**Comment by wisdomboy** [comment]
> This usually only occurs when the account is set to private or the name is misspelled. Other than that, this should not occur. Share me the name and I will look into it.

The address of the live broadcast room is https://www.tiktok.com/ @Maya_fami/live，the name is Maya_fami.

**Comment by kohlerpop1** [comment]
Try connecting with this username `maya_fami`. Aka lowercase and see how that works!

**Comment by wisdomboy** [comment]
> Try connecting with this username `maya_fami`. Aka lowercase and see how that works!

thanks
