### ISSUE TITLE
The wrong gift price

### ISSUE THREAD

**Issue by wisdomboy** [jwdeveloper/TikTokLiveJava#105]
Gift name: Helmet, with two gift IDs of 12559,7057; The prices are 299 and 10 respectively.

I received a gift of 12559 using the onGift function, but in reality, the gift ID given in the live broadcast room was 7057, resulting in a mismatch in the amount. 

thanks for help!

**Comment by wisdomboy** [comment]
I do not know , other gift also have this problem.How to solve this problem fundamentally?

**Comment by kohlerpop1** [comment]
This needs to be resolved by the maintainers. We are discussing the best way to resolve it.

**Comment by wisdomboy** [comment]
> This needs to be resolved by the maintainers. We are discussing the best way to resolve it.

thanks，i have try to do it.
