### ISSUE TITLE
RoomInfo Coin Total

### ISSUE THREAD

**Issue by ivanocj** [jwdeveloper/TikTokLiveJava#107]
Is there a way to show total coins for a live session? For instance, like the number of visitors that is already implemented in RoomInfo.

**Comment by kohlerpop1** [comment]
RoomInfo is populated by what TikTok sends throughout each event and webcast messages. The total coins is never sent to us (that we know of) and would have to be done manually therefore it wont be done in the library. You can easily track the total coins for a live session as I also do it myself in my own application.

**Comment by ivanocj** [comment]
Sure, developers can easily track total coins, but not from the beginning of the live session, isn't it? Also, I tried to sum the ranking but it is not precise, sometimes it doesn't send the correct value of coins sent by an user.

**Comment by LuxuryBoosts** [comment]
I personally track all the gifts for example users send, and log them like this

  "lazarq(kamilek_b_b)": {
    "giftsGiven": 55,
    "gifts": {
      "Rose": 278,
      "GG": 8,
      "W": 4,
      "Soccer": 6
    },
    "totalCoins": 312
  },

so then I can remember everything people do. but you could also have it save to a file and reset every stream, or you could use a temporary variable probably

**Comment by kohlerpop1** [comment]
> Sure, developers can easily track total coins, but not from the beginning of the live session, isn't it? Also, I tried to sum the ranking but it is not precise, sometimes it doesn't send the correct value of coins sent by an user.

You are correct. Not much else you can do besides track from the point you connect to it as the total coins are not passed anywhere else. I do something similar to what @LuxuryBoosts mentioned in terms of tracking the total coins.
