### ISSUE TITLE
Invalid build configuration. Attempt to create a global synthetic for 'Record desugaring' without a global-synthetics consumer.

### ISSUE THREAD

**Issue by mac0ten** [jwdeveloper/TikTokLiveJava#11]
Unable to use it in Android Studio (Java) Backend.

I imported this released jar in android studio dependencies it doesn't have any errors in importing, but the errors is in building the project it got error about : Invalid build configuration. Attempt to create a global synthetic for 'Record desugaring' without a global-synthetics consumer.

--
I have tried these steps added (but still failed to use your jar):

    defaultConfig {
        .....
        multiDexEnabled true
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
        coreLibraryDesugaringEnabled true
    }

**Comment by jwdeveloper** [comment]
Hi, I have never been using Android studio, so unfortunatelly I can't help much

**Comment by jwdeveloper** [comment]
change version of Java from 1.8 you are current using to 16 since tiktok Java was made with Java 16

**Comment by mac0ten** [comment]
> change version of Java from 1.8 you are current using to 16 since tiktok Java was made with Java 16

I tried this solution and it actually removed the errors, Thanks you so much.

**Comment by cxlhyx** [comment]
> change version of Java from 1.8 you are current using to 16 since tiktok Java was made with Java 16

helpfu
