### ISSUE TITLE
Sign Server Rate Limit Reached / Error Http 429

### ISSUE THREAD

**Issue by ivanocj** [jwdeveloper/TikTokLiveJava#113]
I'd like to understand what is the exact value of this rate. Sometimes I see my application taking longer to have it. 

`io.github.jwdeveloper.tiktok.exceptions.TikTokSignServerException: Sign server did not return the x-set-tt-cookie header - ActionResult: {
  "success": true,
  "message": "HttpResponse Code: 429 | Sign server rate limit reached. Try again in 03:02.",
  "content": {
    "statusCode": 429,
    "request": {
      "method": "GET",
      "timeout": "Optional[PT3S]",
      "expectContinue": false,
      "uri": "https://tiktok.eulerstream.com/webcast/fetch?aid=1988&app_language=en-US&app_name=tiktok_web&browser_language=en&browser_name=Mozilla&browser_online=true&browser_plat
form=Win32&browser_version=5.0+%28Windows+NT+10.0%3B+Win64%3B+x64%29+AppleWebKit%2F537.36+%28KHTML%2C+like+Gecko%29+Chrome%2F102.0.5005.63+Safari%2F537.36&client=ttlive-java&cookie
_enabled=true&cursor=&device_platform=web&did_rule=3&fetch_rule=1&focus_state=true&from_page=user&history_len=4&identity=audience&internal_ext=&is_fullscreen=false&is_page_visible=
true&last_rtt=0&live_id=12&msToken=&referer=https%2C+%2F%2Fwww.tiktok.com%2F&resp_content_type=protobuf&room_id=7443147032582179640&root_referer=https%2C+%2F%2Fwww.tiktok.com%2F&sc
reen_height=1152&screen_width=2048&tz_name=Europe%2FBerlin&update_version_code=1.3.0&uuc=1&version_code=180800&webcast_language=en-US&webcast_sdk_version=1.3.0",`

Do anyone already faced this issue? How to overcome it (using proxies, etc)?  Thanks in advance.

**Comment by kohlerpop1** [comment]
You are hitting the rate limit of the Signing Server. How many requests are you sending and how often?
The rate limits have also recently been increased so you should not be hitting this upon normal usage.
A free API key can be found here which also increases your limits even more. https://www.eulerstream.com
If you are still experiencing issues, it might be an issue with your underlying code. Support can be found on this TikTokLive discord. https://discord.gg/raCd2xDvJd

**Comment by kohlerpop1** [comment]
> I'm hitting by a lot, like I am recording data from all the streamers that Tiktok is recommending to my service account user via a web scraper (selenium/chromium driver). So, it's like 5x streamers per hour (minimum!). I definitely think it's time for me to spend some time trying to understand how to create my own sign server... 😥
@ivanocj 
5 streamers per hour is nothing. You should be able to do 5 streamers per minute and not hit the rate limit. Which is why you may have a bigger underlying issue with your code. If you want/need help, you can join the discord and many people can help evaluate your code to ensure it is running properly.
