### ISSUE TITLE
Few bugs report

### ISSUE THREAD

**Issue by SteveNunes** [jwdeveloper/TikTokLiveJava#14]
![image](https://github.com/jwdeveloper/TikTokLiveJava/assets/36564064/30f2e428-4d85-4c9b-ac8f-9743bfa1044e)

![image](https://github.com/jwdeveloper/TikTokLiveJava/assets/36564064/620bb56d-1dae-4727-bd11-b4d490b50bb8)

![image](https://github.com/jwdeveloper/TikTokLiveJava/assets/36564064/df8b2a6c-b787-47bd-a7c1-a60f928130dd)

**Comment by jwdeveloper** [comment]
fixed in 1.0.5
