### ISSUE TITLE
Can't use it as Android Library

### ISSUE THREAD

**Issue by khrlimam** [jwdeveloper/TikTokLiveJava#24]
Hi, i'm trying to use this library on my android project but the build is not successful.
build error message shows up: `Invalid build configuration. Attempt to create a global synthetic for 'Record desugaring' without a global-synthetics consumer.
`

it says error while dexing

**Comment by khrlimam** [comment]
> Mąkę sure you are using Java version 16 in your project

extensive discussion is on discord channel

**Comment by jwdeveloper** [comment]
Currently I'm not planning to support android
