### ISSUE TITLE
Battle Team Information Incorrect

### ISSUE THREAD

**Issue by kohlerpop1** [jwdeveloper/TikTokLiveJava#25]
It seems that either TikTok is sending information improperly, or it is being mapped improperly.
When a battle starts, I print battle started along with the event#toJson(), leading to this!
```
Battle started: {
  "battleId": 7308855855552957189,
  "team1": [],
  "team2": [
    {
      "teamId": 6622598488763842566,
      "users": [
        {
          "id": 0,
          "name": "",
          "profileName": "",
          "picture": {
            "link": ""
          },
          "following": 0,
          "followers": 0,
          "badges": [],
          "attributes": []
        }
      ]
    },
    {
      "teamId": 7150234761369338885,
      "users": [
        {
          "id": 0,
          "name": "",
          "profileName": "",
          "picture": {
            "link": ""
          },
          "following": 0,
          "followers": 0,
          "badges": [],
          "attributes": []
        }
      ]
    }
  ],
  "messageId": 7308855859535530758,
  "roomId": 7308855312177728262,
  "timeStamp": 1701725619780
}
```
This always shows team1 as an empty list and team2 as a list of all the teams.
Anyone else experiencing this issue?

**Comment by jwdeveloper** [comment]
All the remaining events that can not be found in TikTokLive.newClient("asdad"). <- are in "development" state so you should relay on them or use them.

**Comment by kohlerpop1** [comment]
I see. I am currently casting it `((TikTokLiveClientBuilder) TikTokLive.newClient(user))` as lots of the events that are in development I need. But thats ok. I can remap it myself it this is still in development/not fix/working as intended. Thanks for the information!

**Comment by jwdeveloper** [comment]
Why some events are not included? Mostly for two reason 
1. I don't really understand meaning of incoming data
2. They are so rare so it's hard to catch them and map propelly
This reasons applies for me when it comes to the all Battle related events. But If you really willing to use and discover how and when Battels TikTok data works. I can write for you guid how to read and map data from TikTok.

**Comment by kohlerpop1** [comment]
Yes please make a guide for me.
I can also help contribute to the project if I can understand how to read and map the data.

**Comment by jwdeveloper** [comment]
https://github.com/jwdeveloper/TikTokLiveJava/blob/master/collaboration.md?plain=1

I made brief guid, about info about including new events is at the bottom. It's very basic example but I think is good for now. For more informations ask me at discord

**Comment by kohlerpop1** [comment]
> https://github.com/jwdeveloper/TikTokLiveJava/blob/master/collaboration.md
> 
> I made brief guid, info about including new events is at the bottom. It's very basic example but I think is good for now. For more informations ask me at discord

Awesome. I appreciate this so much. I look forward to assisting with this in my free time!
