### ISSUE TITLE
What is the version of the jdk and gradle ?

### ISSUE THREAD

**Issue by kuluoliduo** [jwdeveloper/TikTokLiveJava#26]
> Could not find method dependencyResolutionManagement() for arguments [build_22m01d7psovyv0r5vrwkltdtm$_run_closure4@48593c09] on root project 'TiktokGradleTest' of type org.gradle.api.Project.

What is the version of the jdk and gradle ?
mine is 17 and 8.5

**Comment by jwdeveloper** [comment]
The project was made with Java 16
