### ISSUE TITLE
Remote host terminated the handshake

### ISSUE THREAD

**Issue by wjh1989** [jwdeveloper/TikTokLiveJava#27]
![微信截图_20231211163426](https://github.com/jwdeveloper/TikTokLiveJava/assets/9987443/44c2ceb6-03c1-4a5c-a10a-9bb87da9fa05)

**Comment by jwdeveloper** [comment]
It was one time error or it's occurring over and over?

**Comment by wjh1989** [comment]
over and over, sometimes is "HTTP connect timed out"

**Comment by wjh1989** [comment]
but i used proxy,so i don't know why

**Comment by jwdeveloper** [comment]
This error said that tiktok does rejected your connection request. I've never been dealing with proxies before. The error migth be also cased by your location

**Comment by jwdeveloper** [comment]
For some world regions tiktok is more restrictive

**Comment by wjh1989** [comment]
thanks answer :)
