### ISSUE TITLE
Living room message comment time issue

### ISSUE THREAD

**Issue by llddy** [jwdeveloper/TikTokLiveJava#32]
In [https://github.com/jwdeveloper/TikTokLiveJava/blob/master/API/src/main/proto/data.proto](url)
Message Common{
Int64 createTime=4;
}

[https://github.com/jwdeveloper/TikTokLiveJava/blob/master/API/src/main/java/io/github/jwdeveloper/tiktok/data/events/common/TikTokHeaderEvent.java](url)
```
@Getter
Public class TikTokHeaderEvent extensions TikTokEvent{
  Private final long messageId;
  Private final long roomId;
  Private final long timeStamp;
  Public TikTokHeaderEvent (Common header){
     This (header. getMsgId(), header. getRoomId(), header. getCreatTime());
  }
   //Omit
}
```

**Comment by jwdeveloper** [comment]
This property represends time at which event was created at TikTok server. So it will not be your local computer time

**Comment by llddy** [comment]
> This property represends time at which event was created at TikTok server. So it will not be your local computer time

Understanding error, please close
