### ISSUE TITLE
Exception: Sign server did not return the x-set-tt-cookie header

### ISSUE THREAD

**Issue by pengxiao18** [jwdeveloper/TikTokLiveJava#68]
Exception in thread "main" io.github.jwdeveloper.tiktok.exceptions.TikTokSignServerException: Sign server did not return the x-set-tt-cookie header - ActionResult: {
  "success": true,
  "content": {
    "statusCode": 200,
    "request": {
      "method": "GET",
      "timeout": "Optional[PT3S]",
      "expectContinue": false,
      "uri": "https://tiktok.eulerstream.com/webcast/fetch?aid=1988&app_language=en-US&app_name=tiktok_web&browser_language=en&browser_name=Mozilla&browser_online=true&browser_platform=Win32&browser_version=5.0+%28Windows+NT+10.0%3B+Win64%3B+x64%29+AppleWebKit%2F537.36+%28KHTML%2C+like+Gecko%29+Chrome%2F102.0.5005.63+Safari%2F537.36&client=ttlive-java&cookie_enabled=true&cursor=&device_platform=web&did_rule=3&fetch_rule=1&focus_state=true&from_page=user&history_len=4&identity=audience&internal_ext=&is_fullscreen=false&is_page_visible=true&last_rtt=0&live_id=12&msToken=&referer=https%2C+%2F%2Fwww.tiktok.com%2F&resp_content_type=protobuf&room_id=7350866185530952469&root_referer=https%2C+%2F%2Fwww.tiktok.com%2F&screen_height=1152&screen_width=2048&tz_name=Europe%2FBerlin&update_version_code=1.3.0&uuc=1&version_code=180800&webcast_language=en-US&webcast_sdk_version=1.3.0",
      "version": "Optional.empty",
      "headers": {
        "Accept": [
          "text/html,application/json,application/protobuf"
        ],
        "Accept-Language": [
          "en-US,en; q=0.9"
        ],
        "authority": [
          "www.tiktok.com"
        ],
        "Cache-Control": [
          "max-age=0"
        ],
        "Origin": [
          "https://www.tiktok.com"
        ],
        "Referer": [
          "https://www.tiktok.com/"
        ],
        "User-Agent": [
          "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/102.0.5005.63 Safari/537.36"
        ]
      }
    },
    "headers": {
      ":status": [
        "200"
      ],
      "access-control-allow-origin": [
        "*"
      ],
      "alt-svc": [
        "h3=\":443\"; ma=86400"
      ],
      "cf-cache-status": [
        "DYNAMIC"
      ],
      "cf-ray": [
        "86ac5ae86a169cc9-SIN"
      ],
      "content-type": [
        "application/protobuf"
      ],
      "date": [
        "Wed, 27 Mar 2024 03:39:46 GMT"
      ],
      "nel": [
        "{\"success_fraction\":0,\"report_to\":\"cf-nel\",\"max_age\":604800}"
      ],
      "ratelimit-limit": [
        "12"
      ],
      "ratelimit-policy": [
        "12;w=3600"
      ],
      "ratelimit-remaining": [
        "8"
      ],
      "ratelimit-reset": [
        "1788"
      ],
      "report-to": [
        "{\"endpoints\":[{\"url\":\"https:\\/\\/a.nel.cloudflare.com\\/report\\/v4?s=5rvmlySriAoNc%2FRZ4Ng6FsHIlKv5fuT6pDVEaPOnPCShoRXQUxZWPsEk2z3tIhqDGDz7imwU9opXHZKZrDzsbuMoUI5dCLzLgfJ1jIXB3JdNrfN2LhFDxMbw5jAhg7hu390ZeNEFcu7ksB6xXHyE4KinFf%2B%2F\"}],\"group\":\"cf-nel\",\"max_age\":604800}"
      ],
      "server": [
        "cloudflare"
      ],
      "x-ratelimit-limit": [
        "12"
      ],
      "x-ratelimit-remaining": [
        "8"
      ],
      "x-ratelimit-reset": [
        "1711512574"
      ]
    },
    "body": [],
    "uri": "https://tiktok.eulerstream.com/webcast/fetch?aid=1988&app_language=en-US&app_name=tiktok_web&browser_language=en&browser_name=Mozilla&browser_online=true&browser_platform=Win32&browser_version=5.0+%28Windows+NT+10.0%3B+Win64%3B+x64%29+AppleWebKit%2F537.36+%28KHTML%2C+like+Gecko%29+Chrome%2F102.0.5005.63+Safari%2F537.36&client=ttlive-java&cookie_enabled=true&cursor=&device_platform=web&did_rule=3&fetch_rule=1&focus_state=true&from_page=user&history_len=4&identity=audience&internal_ext=&is_fullscreen=false&is_page_visible=true&last_rtt=0&live_id=12&msToken=&referer=https%2C+%2F%2Fwww.tiktok.com%2F&resp_content_type=protobuf&room_id=7350866185530952469&root_referer=https%2C+%2F%2Fwww.tiktok.com%2F&screen_height=1152&screen_width=2048&tz_name=Europe%2FBerlin&update_version_code=1.3.0&uuc=1&version_code=180800&webcast_language=en-US&webcast_sdk_version=1.3.0",
    "version": "HTTP_2"
  }
}
	at io.github.jwdeveloper.tiktok.TikTokLiveHttpClient.fetchLiveConnectionData(TikTokLiveHttpClient.java:156)
	at io.github.jwdeveloper.tiktok.TikTokLiveClient.tryConnect(TikTokLiveClient.java:170)
	at io.github.jwdeveloper.tiktok.TikTokLiveClient.connect(TikTokLiveClient.java:103)
	at io.github.jwdeveloper.tiktok.TikTokLiveClientBuilder.buildAndConnect(TikTokLiveClientBuilder.java:237)
	at org.example.Main.main(Main.java:23)

**Comment by kohlerpop1** [comment]
@pengxiao18 
Sorry I just now saw this. Normally, this exception only occurs on error code 500. 
However, even with that being said, there is nothing we can do about it. It is the responsibility of the signing server to return that header so we know the cookie to use to send the request to TikTok. Without this header, the request directly to TikTok will fail. So if this occurs, most likely you just need to send the request again.

**Comment by kohlerpop1** [comment]
This was a sign server issue that occurred from latest TikTok update. It has since been fixed!

**Comment by timothy692** [comment]
I am having the same problem as of May 24, are there any fixes available?
