### ISSUE TITLE
At present there are many DISCONNECTED live.

### ISSUE THREAD

**Issue by htliang128** [jwdeveloper/TikTokLiveJava#75]
![image](https://github.com/jwdeveloper/TikTokLiveJava/assets/105912866/77eee04c-fdcb-4cf8-a2ac-4e918e532828)
![image](https://github.com/jwdeveloper/TikTokLiveJava/assets/105912866/54f3edcd-7a0d-408c-ae45-dbc203070946)

**Comment by kohlerpop1** [comment]
Fixed with version 1.6.2
