### ISSUE TITLE
 Sign server did not return the x-set-tt-cookie header 

### ISSUE THREAD

**Issue by ReactorNefg** [jwdeveloper/TikTokLiveJava#79]
io.github.jwdeveloper.tiktok.exceptions.TikTokSignServerException: Sign server did not return the x-set-tt-cookie header - ActionResult: {
  "success": true,
  "content": {
    "statusCode": 502,
    "request": {
      "method": "GET",
      "timeout": "Optional[PT3S]",
      "expectContinue": false,
      "uri": "https://tiktok.eulerstream.com/webcast/fetch?aid=1988&app_language=en-US&app_name=tiktok_web&browser_language=en&browser_name=Mozilla&browser_online=true&browser_platform=Win32&browser_version=5.0+%28Windows+NT+10.0%3B+Win64%3B+x64%29+AppleWebKit%2F537.36+%28KHTML%2C+like+Gecko%29+Chrome%2F102.0.5005.63+Safari%2F537.36&client=ttlive-java&cookie_enabled=true&cursor=&device_platform=web&did_rule=3&fetch_rule=1&focus_state=true&from_page=user&history_len=4&identity=audience&internal_ext=&is_fullscreen=false&is_page_visible=true&last_rtt=0&live_id=12&msToken=&referer=https%2C+%2F%2Fwww.tiktok.com%2F&resp_content_type=protobuf&room_id=7372615119169784608&root_referer=https%2C+%2F%2Fwww.tiktok.com%2F&screen_height=1152&screen_width=2048&tz_name=Europe%2FBerlin&update_version_code=1.3.0&uuc=1&version_code=180800&webcast_language=en-US&webcast_sdk_version=1.3.0",
      "version": "Optional.empty",
      "headers": {
        "Accept": [
          "text/html,application/json,application/protobuf"
        ],
        "Accept-Language": [
          "en-US,en; q=0.9"
        ],
        "authority": [
          "www.tiktok.com"
        ],
        "Cache-Control": [
          "max-age=0"
        ],
        "Origin": [
          "https://www.tiktok.com"
        ],
        "Referer": [
          "https://www.tiktok.com/"
        ],
        "User-Agent": [
          "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/102.0.5005.63 Safari/537.36"
        ]
      }
    },
    "headers": {
      ":status": [
        "502"
      ],
      "alt-svc": [
        "h3=\":443\"; ma=86400"
      ],
      "cache-control": [
        "private, max-age=0, no-store, no-cache, must-revalidate, post-check=0, pre-check=0"
      ],
      "cf-ray": [
        "888fdbaf0e675b7e-VIE"
      ],
      "content-length": [
        "15"
      ],
      "content-type": [
        "text/plain; charset=UTF-8"
      ],
      "date": [
        "Fri, 24 May 2024 19:58:02 GMT"
      ],
      "expires": [
        "Thu, 01 Jan 1970 00:00:01 GMT"
      ],
      "nel": [
        "{\"success_fraction\":0,\"report_to\":\"cf-nel\",\"max_age\":604800}"
      ],
      "referrer-policy": [
        "same-origin"
      ],
      "report-to": [
        "{\"endpoints\":[{\"url\":\"https:\\/\\/a.nel.cloudflare.com\\/report\\/v4?s=gC49nK%2Fk0outcYO5YS0yR9Ke3weiNJdt%2BQii38NrsD66SNRmb%2BrrfF29xhjiKGvaYj6NE2QuBwzWI%2FINWfX%2BYjTBasWMUzjfykYd6f95mpqlPLBMAR3p1UoFBL1S3KIGHF2RJ8PMx1XQ\"}],\"group\":\"cf-nel\",\"max_age\":604800}"
      ],
      "server": [
        "cloudflare"
      ],
      "x-frame-options": [
        "SAMEORIGIN"
      ]
    },
    "body": [
      101,
      114,
      114,
      111,
      114,
      32,
      99,
      111,
      100,
      101,
      58,
      32,
      53,
      48,
      50
    ],
    "uri": "https://tiktok.eulerstream.com/webcast/fetch?aid=1988&app_language=en-US&app_name=tiktok_web&browser_language=en&browser_name=Mozilla&browser_online=true&browser_platform=Win32&browser_version=5.0+%28Windows+NT+10.0%3B+Win64%3B+x64%29+AppleWebKit%2F537.36+%28KHTML%2C+like+Gecko%29+Chrome%2F102.0.5005.63+Safari%2F537.36&client=ttlive-java&cookie_enabled=true&cursor=&device_platform=web&did_rule=3&fetch_rule=1&focus_state=true&from_page=user&history_len=4&identity=audience&internal_ext=&is_fullscreen=false&is_page_visible=true&last_rtt=0&live_id=12&msToken=&referer=https%2C+%2F%2Fwww.tiktok.com%2F&resp_content_type=protobuf&room_id=7372615119169784608&root_referer=https%2C+%2F%2Fwww.tiktok.com%2F&screen_height=1152&screen_width=2048&tz_name=Europe%2FBerlin&update_version_code=1.3.0&uuc=1&version_code=180800&webcast_language=en-US&webcast_sdk_version=1.3.0",
    "version": "HTTP_2"
  },
  "message": "HttpResponse Code:  502"
}
        at io.github.jwdeveloper.tiktok.TikTokLiveHttpClient.fetchLiveConnectionData(TikTokLiveHttpClient.java:182) ~[ticktok-1.0-SNAPSHOT.jar:?]
        at io.github.jwdeveloper.tiktok.TikTokLiveClient.tryConnect(TikTokLiveClient.java:166) ~[ticktok-1.0-SNAPSHOT.jar:?]
        at io.github.jwdeveloper.tiktok.TikTokLiveClient.connect(TikTokLiveClient.java:96) ~[ticktok-1.0-SNAPSHOT.jar:?]
        at io.github.jwdeveloper.tiktok.TikTokLiveClientBuilder.buildAndConnect(TikTokLiveClientBuilder.java:243) ~[ticktok-1.0-SNAPSHOT.jar:?]
        at ru.rustworker.ticktok.commands.comand.lambda$onCommand$6(comand.java:110) ~[ticktok-1.0-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_20_R3.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.20.4.jar:git-Paper-496]
        at org.bukkit.craftbukkit.v1_20_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[paper-1.20.4.jar:git-Paper-496]
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[paper-1.20.4.jar:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) ~[?:?]
        at java.lang.Thread.run(Unknown Source) ~[?:?]

**Comment by kohlerpop1** [comment]
https://discord.com/channels/977648006063091742/978702822847692820/1243647329110720573

![image](https://github.com/jwdeveloper/TikTokLiveJava/assets/70915561/ec34cb15-214c-4ba0-b12f-189dd2ee434d)
