### ISSUE TITLE
420

### ISSUE THREAD

**Issue by htliang128** [jwdeveloper/TikTokLiveJava#83]
https://tiktok.eulerstream.com/webcast/fetch?aid=1988&app_language=en&app_name=tiktok_web&browser_language=en&browser_name=Mozilla&browser_online=true&browser_platform=Win32&browser_version=5.0+%28Windows+NT+10.0%3B+Win64%3B+x64%29+AppleWebKit%2F537.36+%28KHTML%2C+like+Gecko%29+Chrome%2F102.0.5005.63+Safari%2F537.36&client=ttlive-java&cookie_enabled=true&cursor=&device_platform=web&did_rule=3&fetch_rule=1&focus_state=true&from_page=user&history_len=4&identity=audience&internal_ext=&is_fullscreen=false&is_page_visible=true&last_rtt=0&live_id=12&msToken=&referer=https%2C+%2F%2Fwww.tiktok.com%2F&resp_content_type=protobuf&room_id=7373322492695415594&root_referer=https%2C+%2F%2Fwww.tiktok.com%2F&screen_height=1152&screen_width=2048&tz_name=Europe%2FBerlin&update_version_code=1.3.0&uuc=1&version_code=180800&webcast_language=en&webcast_sdk_version=1.3.0

TikTok returns 420 with in body {"error": "Offline due to DDoS attack.", "status": 420}

Is there another available api?

**Comment by kohlerpop1** [comment]
Nope. Have to wait for DDoS to stop.
