### ISSUE TITLE
Possible Disconnect manually ?

### ISSUE THREAD

**Issue by KendaFR** [jwdeveloper/TikTokLiveJava#99]
Hello,

is it possible to disconnect manually after a buildAndConnect?

For example, I'm making a minecraft game with several people, and I'd like to be able to make them disconnect (typing error or other).

Thx

**Comment by jwdeveloper** [comment]
Yes, there is Disconnect method

**Comment by KendaFR** [comment]
Oh thx ! 
Oh, and I'd like to not display the error if the user is not found, is there a way?

I use the “onError” event but I have a console error, which I wouldn't like to have :)

**Comment by jwdeveloper** [comment]
`onError` handles are error that was invoked after the `Connection`. The error you mentioned is thrown
obviously before connecting to live.

To avoid it you need to wrap you code with `try {} cache{}`

```java

try
{
TikTokLive.create("Mike").buildAndConnect();
}
cache(Exception e)
{
//pass
}
```

**Comment by KendaFR** [comment]
Oh okay, thx :D
